language: android

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5

jdk:
  - oraclejdk8

before_script:
  - pip install --user codecov

after_success:
  - codecov
  - .buildscript/deploy_snapshot.sh

notifications:
  email: false

sudo: false

cache:
  directories:
  - $HOME/.m2

script:
  - ./gradlew assembleRelease test